---
title: "Exploratory 1"
output: pdf_document
---

Connect to SQLITE database and get data from the database
```{r}
con <- dbConnect(SQLite(), "../../Data/RDS/Data/FPA_FOD.sqlite")
res<-dbGetQuery(con, "SELECT  FIRE_YEAR, FIRE_SIZE, FIPS_NAME,FIPS_CODE, STATE, LATITUDE, LONGITUDE FROM Fires WHERE (FIRE_SIZE > 5) AND (FIRE_YEAR < 2022)")
dbDisconnect(con)
```

sum total acre burn for each county
```{r}
fire_sum <- aggregate(res$FIRE_SIZE,list(res$FIPS_CODE),FUN=sum)
colnames(fire_sum) <- c('fips','Total_Burn')
fire_sum
```

Get Census Dataset (Area)
```{r}
county_size <- read_excel('../../Data/Census Data/LND01.xls')
county_size <- county_size[!(as.numeric(county_size$STCOU)%%1000 == 0),]
county_size <- county_size[,c('Areaname','STCOU','LND110210D')]

colnames(county_size)[colnames(county_size)=='STCOU'] <- 'fips'
colnames(county_size)[colnames(county_size)=='LND110210D'] <- 'Area'
county_size$Area <- county_size$Area*640 #Get into acreas instead of square miles
county_size

```

Combine dataset and get the percentage of acrea burn for each county
```{r}
county_burn <- full_join(county_size,fire_sum,by='fips')
county_burn$Total_Burn[is.na(county_burn$Total_Burn)] <- 0
county_burn$Per_Area <- county_burn$Total_Burn/county_burn$Area
county_burn <- county_burn[order(county_burn$Per_Area,decreasing=TRUE),]
county_burn
```

```{r}
plot_usmap(regions='county',data = county_burn[,c('fips','Per_Area')], values = "Per_Area", color='gray') + 
  scale_fill_continuous(
    low = "white", high = "red", name = "Percentage of county burn", label = scales::comma
  ) + theme(legend.position = "right")
```


